/*
 * EffectType.h
 *
 *  Created on: 2017. dec. 13.
 *      Author: Acer
 */

#ifndef EFFECTTYPE_H_
#define EFFECTTYPE_H_



#define EFFECT_TRANSITION_DOT_UP_HSV (0)


#define EFFECT_LUMU (1)
#define EFFECT_CANDLE (2)
#define EFFECT_FIRE (3)

#define EFFECT_TRANSITION_RADII_UP_HSV (4)
#define EFFECT_TRANSITION_STAR_UP_HSV (5)

#define EFFECT_TRANSITION_DOT_RANDOM_HSV (6)
#define EFFECT_TRANSITION_RADII_RANDOM_HSV (7)
#define EFFECT_TRANSITION_STAR_RANDOM_HSV (8)

#define MIN_EFFECT (EFFECT_TRANSITION_DOT_UP_HSV)
#define MAX_EFFECT (EFFECT_TRANSITION_STAR_RANDOM_HSV)

#define EFFECT_START EFFECT_TRANSITION_DOT_UP_HSV;

#endif /* EFFECTTYPE_H_ */
